# Generated by Django 5.1.2 on 2024-11-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='author',
        ),
    ]
